"""
Scripts to consume amqp messages generated by donkey car.

Usage:
rc-keras-steering.py (-u USERNAME | --mqtt-username=USERNAME) --mqtt-password=PASSWORD --mqtt-broker=HOSTNAME

Options:
-h --help                                       Show this screen.
-u USERID --mqtt-username=USERNAME              MQTT user
-p PASSWORD --mqtt-password=PASSWORD            MQTT password
-b HOSTNAME --mqtt-broker=HOSTNAME              MQTT broker host
-c CLIENT_ID --mqtt-client-id=CLIENT_ID         MQTT client id
-m MODEL_PATH --tf-model-path                   Tensorflow model path

"""
import json
import logging

from docopt import docopt
import paho.mqtt.client as mqtt

from steering.tensorflowlite import SteeringPart

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

default_client_id = "robocar-keras-steering"


def start_mqtt_client(broker_host: str, user: str, password: str, client_id: str, part: SteeringPart,
                      steering_topic: str):
    logger.info("Start keras-steering part")
    client = mqtt.Client(client_id=client_id, clean_session=True, userdata=None, protocol=mqtt.MQTTv311)
    client.username_pw_set(username=user, password=password)

    def on_message(client: mqtt.Client, userdata: SteeringPart, msg: mqtt.MQTTMessage):
        print(msg.topic + " " + str(msg.payload))
        steering = userdata.get_steering(msg.payload)
        payload = json.dumps(steering)

        client.publish(topic=steering_topic,
                       payload=payload,
                       qos=0,
                       retain=False)

    client.on_message = on_message
    client.user_data_set(part)
    client.username_pw_set(user, password)
    client.connect(host=broker_host, port=1883, keepalive=60)
    client.loop_forever()

    return client


def execute_from_command_line():
    args = docopt(__doc__)
    steering_part = SteeringPart(model_path=args["--tf-model-path"])

    start_mqtt_client(broker_host=args["--mqtt-broker"],
                      user=args["--mqtt-username"],
                      password=args["--mqtt-password"],
                      client_id=args["--mqtt-client-id"],
                      steering_topic=args["--mqtt-topic-steering"],
                      part=steering_part
                      )
